services:
  backend:
    container_name: bookmarkmanager-backend
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: bookmarkmanager-postgres
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bookmarkmanager
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
  web:
    container_name: bookmarkmanager-web
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started