ktor:
  application:
    modules:
      - me.atsteffe.ApplicationKt.module
  deployment:
    port: 8080
  development: true

jwt:
  secret: '%env:JWT_SECRET%'
  issuer: "bookmarkmanager"
  audience: "bookmarkmanager-users"
  realm: "BookmarkManager"
