ktor:
  application:
    modules:
      - me.atsteffe.ApplicationKt.module
  deployment:
    port: 8080
    watch:
      - classes
      - resources
  development: true

jwt:
  secret: "%env:JWT_SECRET%"
  issuer: "bookmarkmanager"
  audience: "bookmarkmanager-users"
  realm: "BookmarkManager"

storage:
  driverClassName: "org.postgresql.Driver"
  jdbcURL: "jdbc:postgresql://localhost:5432/bookmarkmanager"
  user: "postgres"
  password: ""
